### ISSUE TITLE
Field name case

### ISSUE THREAD

**Issue by keatonwalker** [agrc-widgets/sherlock#6]
Creating a WebAPI provider with searchField that has the same case as the field name in the SGID doesn't always work.

Sherlock uses Provider searchField string to access object properties [here](https://github.com/agrc-widgets/sherlock/blob/f17b893f9e4a12e9cf459c80ac0b5869e7d72c4b/Sherlock.js#L481) and it caused problems when searchField is not uppercase.

**Comment by steveoh** [comment]
I don't understand. Will you give an example.

**Comment by keatonwalker** [comment]
Sure. This provider caused errors for me:

```
         var countiesProvider = new WebAPI(
                config.apiKey,
                'SGID10.LOCATION.ZoomLocations',
                'Name'
            );
```

The provider searchField `'Name'` has the same case as the field in ZoomLocations but it will cause Sherlock to error unless you provide the searchField in uppercase to the Provider constructor.

**Comment by steveoh** [comment]
What is the exact error and stack trace of you have it?

**Comment by keatonwalker** [comment]
Here is the stack trace:

```
dojo/promise/instrumentation.js:20 Error: sherlock.Sherlock_processResults: Cannot read property 'slice' of undefined(…) "Error: sherlock.Sherlock_processResults: Cannot read property 'slice' of undefined
    at _processResults (sherlock/Sherlock.js:425:23)
    at eval (sherlock/Sherlock.js:382:22)
    at eval (dojo/_base/lang.js:386:55)
    at signalListener (dojo/Deferred.js:37:21)
    at signalWaiting (dojo/Deferred.js:28:4)
    at Deferred.resolve (dojo/Deferred.js:192:5)
    at eval (agrc/modules/WebAPI.js:149:25)
    at signalListener (dojo/Deferred.js:37:21)
    at signalWaiting (dojo/Deferred.js:28:4)
    at Deferred.resolve (dojo/Deferred.js:192:5)
    ----------------------------------------
    rejected at signalDeferred (dojo/Deferred.js:84:15)
    at signalListener (dojo/Deferred.js:55:5)
    at signalWaiting (dojo/Deferred.js:28:4)
    at Deferred.resolve (dojo/Deferred.js:192:5)
    at eval (agrc/modules/WebAPI.js:149:25)
    at signalListener (dojo/Deferred.js:37:21)
    at signalWaiting (dojo/Deferred.js:28:4)
    at Deferred.resolve (dojo/Deferred.js:192:5)
    at signalDeferred (dojo/Deferred.js:81:15)
    at signalListener (dojo/Deferred.js:52:6)
    ----------------------------------------
Error
    at Promise.Deferred.then.promise.then [as then] (dojo/Deferred.js:252:24)
    at _search (sherlock/Sherlock.js:378:48)
    at eval (sherlock/Sherlock.js:323:22)
    at eval (dojo/_base/lang.js:386:55)"logError @ dojo/promise/instrumentation.js:20(anonymous function) @ dojo/promise/instrumentation.js:67filter @ dojo/_base/array.js:333logRejected @ dojo/promise/instrumentation.js:62
sherlock/Sherlock.js:663 sherlock.Sherlock:_toggleTable [false]
```

In debugging I saw that accessing the object property by string is returning undefined [here](https://github.com/agrc-widgets/sherlock/blob/f17b893f9e4a12e9cf459c80ac0b5869e7d72c4b/Sherlock.js#L481) and then the [slice](https://github.com/agrc-widgets/sherlock/blob/f17b893f9e4a12e9cf459c80ac0b5869e7d72c4b/Sherlock.js#L484) is failing just after that.

**Comment by stdavis** [comment]
That's strange. It should be making the request to the web api with the `identical` value for the `attributeStyle` option for that service. I'd like to take a look at the request on your machine when you get a chance.

**Comment by stdavis** [comment]
This is an upstream bug in the web api. Closing in favor of: https://github.com/agrc/api.mapserv.utah.gov/issues/29
